(ns thaenalpha.rand-oh-my-posh-themes)
(defn -main []
  (println (rand-nth ['agnoster.omp.json
                      'agnosterplus.omp.json
                      'aliens.omp.json
                      'avit.omp.json
                      'blueish.omp.json
                      'bubblesline.omp.json
                      'bubbles.omp.json
                      'cert.omp.json
                      'cinnamon.omp.json
                      'darkblood.omp.json
                      'emodipt.omp.json
                      'fish.omp.json
                      'gmay.omp.json
                      'half-life.omp.json
                      'honukai.omp.json
                      'hotstick.minimal.omp.json
                      'huvix.omp.json
                      'iterm2.omp.json
                      'jandedobbeleer.omp.json
                      'jonnychipz.omp.json
                      'lambda.omp.json
                      'marcduiker.omp.json
                      'material.omp.json
                      'microverse-power.omp.json
                      'mt.omp.json
                      'negligible.omp.json
                      'nu4a.omp.json
                      'paradox.omp.json
                      'pararussel.omp.json
                      'pixelrobots.omp.json
                      'powerlevel10k_classic.omp.json
                      'powerlevel10k_lean.omp.json
                      'powerlevel10k_modern.omp.json
                      'powerlevel10k_rainbow.omp.json
                      'powerline.omp.json
                      'pure.omp.json
                      'remk.omp.json
                      'robbyrussel.omp.json
                      'slimfat.omp.json
                      'slim.omp.json
                      'sorin.omp.json
                      'space.omp.json
                      'spaceship.omp.json
                      'star.omp.json
                      'stelbent.minimal.omp.json
                      'tonybaloney.omp.json
                      'ys.omp.json
                      'zash.omp.json])))
