(ns thaenalpha.rand-oh-my-posh-themes)
(defn -main []
  (println (rand-nth ['agnoster
                      'agnosterplus
                      'aliens
                      'avit
                      'blueish
                      'bubblesline
                      'bubbles
                      'cert
                      'cinnamon
                      'darkblood
                      'emodipt
                      'fish
                      'gmay
                      'half-life
                      'honukai
                      'hotstick.minimal
                      'huvix
                      'iterm2
                      'jandedobbeleer
                      'jonnychipz
                      'lambda
                      'marcduiker
                      'material
                      'microverse-power
                      'mt
                      'negligible
                      'nu4a
                      'paradox
                      'pararussel
                      'pixelrobots
                      'powerlevel10k_classic
                      'powerlevel10k_lean
                      'powerlevel10k_modern
                      'powerlevel10k_rainbow
                      'powerline
                      'pure
                      'remk
                      'robbyrussel
                      'slimfat
                      'slim
                      'sorin
                      'space
                      'spaceship
                      'star
                      'stelbent.minimal
                      'tonybaloney
                      'ys
                      'zash])))
